<?php

class loginController extends Controller {

    private $_acceso;	private $_login;	
    public function __construct() {
        parent::__construct();
        $this->_acceso = $this->loadModel('usuario', 'admin');		$this->_login = $this->loadModel('login');		
    }

    public function index() {
        if (Session::get('autenticado')) {		//actualizacion inmedita		    $condicion = "usu.usu_login='".Session::get('usu')."'";             $row = $this->_acceso->consultar($condicion);			Session::set('level', $row[0]['rol_key']);            Session::set('login', $row[0]['usu_login']);            Session::set('usuario', $row[0]['usu_nombre'] . " " . $row[0]['usu_apellidos']);            Session::set('foto', $row[0]['usu_foto']);            Session::set('id_usuario', $row[0]['usu_key']);		    $this->redireccionar("login/panel");		
        }        $this->_view->assign('titulo', 'Iniciar Sesion');        $this->_view->setJsPlugin(array('jquery.validate'));        $this->_view->setJs(array('validar','validarcorreo'));		
        if ($this->getInt('enviar') == 1) {            //$condicion = "usu.usu_login='{$this->getTexto('usuario')}'";             //$row = $this->_acceso->consultar($condicion);            $comprobar = 0;						$tabla = "";            if ($this->getTexto('empleado') == 'on') {                $condicion = "usu.usu_login='{$this->getTexto('usuario')}'";                $row = $this->_acceso->consultar($condicion);                $tabla = "usu";            } else {                $condicion = "cli_login='{$this->getTexto('usuario')}'";                $row = $this->_cliente->consultar($condicion);                $tabla = "cli";            }						            foreach ($row as $nombre) {                if ($nombre['usu_password'] == Hash::getHash('sha1', $this->getTexto('pass'), $nombre['usu_key'])) {                    $comprobar = 1;                    break;                }            }
            if ($comprobar != 1) {                $this->_view->assign('_error', 'Usuario y/o password incorrectos');				$this->_view->assign('_tipo_error', 1);				$this->_view->renderizar('index');				                exit;            }
            if ($nombre['usu_estado'] != 1) {                $this->_view->assign('_error', 'Este usuario no esta habilitado');				$this->_view->assign('_tipo_error', 2);                $this->_view->renderizar('index');                exit;            }			Session::set('usu', $this->getTexto('usuario'));			
            Session::set('autenticado', true);            			 if ($this->getTexto('empleado') == 'on') {                Session::set('level', $nombre['rol_key']);            } else {                Session::set('level', 0);            }			//echo Session::get('level');			            Session::set('login', $nombre[$tabla .'_login']);            Session::set('usuario', $nombre[$tabla .'_nombre'] . " " . $nombre['usu_apellidos']);            Session::set('foto', $nombre[$tabla .'_foto']);            Session::set('id_usuario', $nombre[$tabla .'_key']);            Session::set('tiempo', time());			            $this->redireccionar('login/panel');
        }

        $this->_view->renderizar('index','inicio');
    }

    public function panel() {				//$this->_view->setCss(array('inettuts'));		$this->_view->setJS(array('validar'));
        		if (session::get('autenticado')) {            $this->_view->assign('titulo', 'Panel de Sesi&oacute;n');												$condicion = " pro_bit.des_usu_key = ".Session::get("id_usuario")." and pro_bit.pro_bit_estado!=0 " ;			$historial = $this->_login->inicio($condicion);								$historialtarea = $this->_login->inicio2();						/*generamos la vista*/			$proyectos=array();			/*sacamos lso proyectos*/			$datos=array();			$datosT=array();			for($i=0;$i<count($historial);$i++)				{					$add = array(									'proyecto_key'=>$historial[$i]['pro_pro_key'],									'proyecto_nombre'=>$historial[$i]['pro_pro_nombre'],									'tareas'=>$this->tareas($historial[$i]['pro_pro_key'],$historial)																	);					if(count($datos)>0)						{						if( !in_array($add,$datos))							array_push($datos,$add);											}					else						{							array_push($datos,$add);											}				}			/*sacamos las tareas*/											for($i=0;$i<count($historialtarea);$i++)				{									$add = array(									'proyecto_key'=>$historialtarea[$i]['pro_pro_key'],									'proyecto_nombre'=>$historialtarea[$i]['pro_pro_nombre'],									'tarea'=>$this->tareasLista($historialtarea[$i]['pro_pro_key'],$historialtarea)																	);					if(count($datosT)>0)						{						if( !in_array($add,$datosT))							array_push($datosT,$add);											}					else						{							array_push($datosT,$add);											}				}									$this->_view->assign('vista', $datos);			$this->_view->assign('vistatarea', $datosT);									$this->_view->renderizar('panel','inicio');        } else {            $this->redireccionar('index');
        }
    }
	function tareas($id_proyecto,$vector)	{	$tarea=array();	for($i=0;$i<count($vector);$i++)				{					if ($id_proyecto==$vector[$i]['pro_pro_key'] )						{							$add=array(										'tarea_key'=>$vector[$i]['pro_tar_key'],										'tarea_nombre'=>$vector[$i]['pro_tar_nombre'],										'actividades'=>$this->actividad($vector[$i]['pro_tar_key'],$vector)									   );							if(count($tarea)>0)								{									if( !in_array($add,$tarea))										array_push($tarea,$add);													}							else								{									array_push($tarea,$add);													}						}				}	return $tarea;		}	function actividad($id_tarea,$vector)	{	$actividad=array();	for($i=0;$i<count($vector);$i++)				{					if ($id_tarea==$vector[$i]['pro_tar_key'])						{							$add=array(										'actividad_key'=>$vector[$i]['pro_bit_key'],										'actividad_nombre'=>$vector[$i]['pro_bit_observacion'],										'actividad_fecha'=>$vector[$i]['pro_bit_fecha_creacion'],																		   );							if(count($actividad)>0)								{									if( !in_array($add,$actividad))										array_push($actividad,$add);													}							else								{									array_push($actividad,$add);													}						}				}	return $actividad;		}	
    function tareasLista($id_proyecto,$vector)	{			$tarea=array();	for($i=0;$i<count($vector);$i++)				{					if ($id_proyecto==$vector[$i]['clave'] )						{							$add=array(										'tarea_key'=>$vector[$i]['pro_tar_key'],										'tarea_nombre'=>$vector[$i]['pro_tar_nombre'],										'terminado'=>$vector[$i]['pro_tar_terminado'],										'aprobado'=>$vector[$i]['pro_tar_aprobado']									   );							if(count($tarea)>0)								{									if( !in_array($add,$tarea))										array_push($tarea,$add);													}							else								{									array_push($tarea,$add);													}						}				}	return $tarea;		}		public function cerrar() {        Session::destroy();        $this->redireccionar();    }
	 public function restablecer() {                $this->_view->assign('titulo', 'Genera una nueva clave de acceso');        $condicion = " usu.usu_email = '{$_POST['correor']}'";        $row = $this->_acceso->consultar($condicion);        $pass = Hash::generarPass();        $this->_acceso->actualizarPassword(Hash::getHash('sha1', $pass, $row[0]['usu_key']), $id);        if ($row[0]['usu_email']) {            $body = "Cordial Saludo<br/>                La presente es para informar los datos de conexion al aplicativo " . APP_NAME . ". A continuacion se informan los datos.<br/><br/>                Usuario: " . $row[0]['usu_login'] . "<br/>" . "Password: " . $pass . "<br/><br/>                Podra acceder por medio de la pagina <a href='" . BASE_URL . "'>" . BASE_URL . "</a>";            $this->getLibrary("xpm" . DS . "MAIL");            //require_once 'libs/xpm/MAIL.php';            $m = new MAIL;            $m->From(EMAIL_REMITENTE, EMAIL_NOMBRE_REMITENTE); // set from address            $m->AddTo($row[0]['usu_email']); // add to address            $m->Subject('Reset Contrase&ntilde;a'); // set subject            $m->html($body);            $c = $m->Connect(EMAIL_HOST, (int) EMAIL_SALIDA, EMAIL_USER, EMAIL_PASS) or die(print_r($m->Result));            $m->Send($c);            $m->Disconnect();        }        $this->redireccionar('index', 'login');    }
}

?>